heart.train<-read.csv(file="train_values.csv",stringsAsFactors=FALSE,header=TRUE)
tail(heart.train)
heart.test<-read.csv(file="test_values.csv",stringsAsFactors=FALSE,header=TRUE)
str(heart.test)	

heart.train$IsTrainset<-TRUE
heart.test$IsTrainset<-FALSE
ncol(heart.train)
ncol(heart.test)
heart.test$heart_disease_present<-NA
heart.full<-rbind(heart.train,heart.test)
table(heart.full$IsTrainset)
str(heart.train)
heart.train<-heart.full[heart.full$IsTrainset==TRUE,]
tail(heart.train)
heart.test<-heart.full[heart.full$IsTrainset==FALSE,]
heart.train$heart_disease_present<-as.factor(heart.train$heart_disease_present)
heart.equation<-"heart_disease_present~slope_of_peak_exercise_st_segment+thal+chest_pain_type+num_major_vessels+fasting_blood_sugar_gt_120_mg_per_dl+resting_ekg_results+sex"
heart.formula<-as.formula(heart.equation)
heart.model<-glm(heart.formula,family=binomial(link="logit"),data=heart.train)
heart<-predict(heart.model,newdata=heart.test,type="response")
patient_id<-heart.test$patient_id
output.df<-as.data.frame(patient_id)
output.df$heart_disease_present<-heart
tail(output.df)
write.csv(output.df,file="submission_format.csv",row.names=FALSE)
